version: "3.8"

services:
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - api_network

    app:
        image: alonecat/photo-stock-api-1:latest
        build:
            context: .
            dockerfile: Dockerfile
       # ports:
        #    - "9000:9000"
       # volumes:
           # - app_storage:/var/www/html/storage
           # - app_cache:/var/www/html/bootstrap/cache
        networks:
            - api_network
        environment:
            - APP_ENV=production
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        depends_on:
            - mysql
    nginx:
        image: alonecat/photo-stock-nginx-1:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        ports:
            - "8080:8080"
        networks:
            - api_network
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 10s


networks:
    api_network:
        driver: overlay

volumes:
    mysql_data:
    app_storage:
    app_cache:
